// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs08JfddFVdg6hhhlzMvzjxk4BpvpqG6A',
    appId: '1:68061730751:web:22836b05d63ef2903df30a',
    messagingSenderId: '68061730751',
    projectId: 'stockly-52b05',
    authDomain: 'stockly-52b05.firebaseapp.com',
    storageBucket: 'stockly-52b05.firebasestorage.app',
    measurementId: 'G-20GEC5SF62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3rAOlhPJgldpdWlHpJpj_8YR_5pPZeM',
    appId: '1:68061730751:android:3dc7c1303b584d623df30a',
    messagingSenderId: '68061730751',
    projectId: 'stockly-52b05',
    storageBucket: 'stockly-52b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz04EOS4TOF18TjAHsPgnHKQNWg9zA7sQ',
    appId: '1:68061730751:ios:bba852bfe242ffa43df30a',
    messagingSenderId: '68061730751',
    projectId: 'stockly-52b05',
    storageBucket: 'stockly-52b05.firebasestorage.app',
    iosBundleId: 'com.example.dharaniStockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz04EOS4TOF18TjAHsPgnHKQNWg9zA7sQ',
    appId: '1:68061730751:ios:bba852bfe242ffa43df30a',
    messagingSenderId: '68061730751',
    projectId: 'stockly-52b05',
    storageBucket: 'stockly-52b05.firebasestorage.app',
    iosBundleId: 'com.example.dharaniStockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRID6VJNzJ0zy0Cmd7Nk9O9bq0eGlMytw',
    appId: '1:68061730751:web:91cd08bfb57fba793df30a',
    messagingSenderId: '68061730751',
    projectId: 'stockly-52b05',
    authDomain: 'stockly-52b05.firebaseapp.com',
    storageBucket: 'stockly-52b05.firebasestorage.app',
    measurementId: 'G-PWWVH2Z1QR',
  );

}